export const ROVER_ENTER_DURATION_MS = 5200;
export const BUTTON_ENTER_DURATION_MS = 4200;
export const ENTER_PHASE_DURATION_MS = Math.max(ROVER_ENTER_DURATION_MS, BUTTON_ENTER_DURATION_MS);
export const PRESS_DURATION_MS = 1300;
export const POST_ARRIVAL_DELAY_MS = 2000;
export const FLOAT_TRIGGER_DELAY_MS = 220;
export const PRE_WARNING_DELAY_MS = 2000;
export const WARNING_PHASE_MS = 1600;
